var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                                    o o      xx                  x!!!x          ",
   "                                                                 xx!xx          ",
   "                                   xxxxx                          xvx           ",
   "                                                                            xx  ",
   "  xx                                      o o                                x  ",
   "  x                     o                                                    x  ",
   "  x                                      xxxxx                             o x  ",
   "  x          xxxx       o                                                    x  ",
   "  x  @       x  x   y                       y                      xxxxx     x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxttxx   xxxxxxxxxxxxxxxxxttx     xxxxxxxxx   xxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                    ",
   "                                                                                                    ",
   "                                                                                                    ",
   "                                                                                                    ",
   "                                                                                                    ",
   "                                                                                                    ",
   "                                                                                                    ",
   "                                                                                                    ",
   "                                       o                                                            ",
   "                                                                                                    ",
   "                                       o                                                            ",
   "                                                                                                    ",
   "                                      xx                                                            ",
   "                                             o o o o o                                              ",
   "                                                              y                                     ",
   "                                   xxx      xxxxxxxxxxx    xxxxxxx                            x     ",
   "                                                                 xxxxxx                       x     ",
   "                                             x         x                    o                 x     ",
   " x                              xxxx        x!x       x!x                 xxx                 x     ",
   " x                                         x!!!x  o  x!!!x                      o             x     ",
   " x                                          x!x   o   x!x                     xxx             x     ",
   " x                         xttxx                                                    o         x     ",
   " x                                                                                xxx         x     ",
   " x                                         xxxxxx!!!xxxxxx                                    x     ",
   " x                   xxttxx               xx             xx                                   x     ",
   " x                   x    x              xx               xx   y          o                   x     ",
   " x @                 x    x   y   xxxttxxx                 xxxxxxxx                     ooo   x     ",
   " xxxx!!!xxx!!!xxx!!!xx    xxxxxxxxx                               xxxxxxxx!!!xxx!!!!!xxxxxxxxxx     ",
   "    xxxxx xxxxx xxxxx                                                    xxxxx xxxxxxx              ",
   "                                                                                                    "],
  ["                                                                                                     ",
   "                                                 o                                                   ",
   "                                                 o                                                   ",
   "                                                 o                                       x           ",
   "                                               xxxxxx                                    x           ",
   "                       o              xxxxxx!!!x    x!!!xxxxxx                           x           ",
   "                      xxx    xxxxxx!!!x    xxxxx    xxxxx    x!!!xxxxxx    xxx           x           ",
   "                                  xxxxx                      xxxxx          o            x           ",
   "                 o                              o o                                      x           ",
   "                xxx                            xxxxx                      xx xx          x           ",
   "                                                                                         x           ",
   "                       o                                           y              o  o   x           ",
   "                      xxx                 xxxxx!!!!!xxxxx     xxxxxxxxxxxx     xxxxxxxxxxx           ",
   "                 o                       xx   xxxxxxx   x                     xx                     ",
   "                xxx                     xx              x                    xx                      ",
   "                                 o o o xx               x                   xx                       ",
   "                                xxxxxxxx                x   y   x!!!x   o  xx                        ",
   "  x           xx   xx          xx                       xxxxxxxxx!!!xxxxxxxx                         ",
   "  x                           xx                                xxxxx                                ",
   "  x                          xx                                                                      ",
   "  x           xxxxxxx     xxxx                                                                       ",
   "  x           x     x!!!!!x                                                                          ",
   "  x      ttxxxx     xxxxxxx                                                                          ",
   "  x           x                                                                                      ",
   "  x @         x                                                                                      ",
   "  xxxxxxx!!!!!x                                                                                      ",
   "        xxxxxxx                                                                                      ",
   "                                                                                                     ",
   "                                                                                                     ",
   "                                                                                                     "],
  ["                                                                                              ",
   "                                                                                              ",
   "                                                                                              ",
   "                                                                                              ",
   "                                                                                              ",
   "                                                                                              ",
   "                                                                     y                        ",
   "                                                                   xxxxx                      ",
   "                                                                   x!!!x                      ",
   "            xx            xx                                       x!!!x                      ",
   "           x!!x          x!!x                   o  o               x!!!x           x          ",
   "          x!!!!x        x!!!!x                xxxxxxxx           o x!!!x           x          ",
   "           x!!x          x!!x                 !x     x             x!!!x           x          ",
   "   x                                         o!x     x!!!!!x       x!!!x           x          ",
   "   x                                     xxxxxxx     xxxxxxxx   xxxxxxxx           x          ",
   "   x             o   o                                                             x          ",
   "   x           xxxttxxxx          xttxx                       o                    x          ",
   "   x     o                   o                               xxx                   x          ",
   "   x    xxx      o   o      xxx                   y      xx                        x          ",
   "   x           xxxxxxxxx                      xxxxxxxxx                            x          ",
   "   x      y                  y                x       x              o   o   o     x          ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          x       x!!!!!!!!!xxxxxxxxxxxxxxxxxxxx          ",
   "   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx      x       x!!!!!!!!!x                             ",
   "   x                                          x       x!!!!!!!!!x                             ",
   "   x        o       o       o              xxxx       xxxxxxxxxxx                             ",
   "   x                                    xxxx                                                  ",
   "   x                                  xxx                                                     ",
   "   x                                xxx                                                       ",
   "   x                               xx                                                         ",
   "   x @                            xx                                                          ",
   "   xxxxx!!!!!xxxxx!!!!!xxxxx!!!!!xx                                                           "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
